env: gdev

server:
  port: 8181

spring:
#  redis:
#    host: st01nbx01
  mvc:
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    #不要为我们工程中的资源文件建立映射
    add-mappings: false

# 自定义
restfulApi:
  generalRecordUrl: http://localhost:3306/general
  clockRecordUrl: http://localhost:3306/clock