env: default

spring:
    application:
        name: core-service
    profiles:
      active:
        - gdev
#    profiles:这个用来指定多环境下使用哪一个环境，此处是指明使用application-prd.yml
#        active: prd  没有用profiles属性就说明默认使用application.yml
